name: fancy_avatar
description: Flutter package providing a fancy looking avatar widget class.
version: 0.0.1
repository: https://github.com/pabello/flutter_fancy_avatar

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

  # assets:
  #   - images/a_dot_burr.jpeg
